title: Rory Bain 
email: rorydbain@gmail.com
description: >-
  I'm Rory, I'm a software engineer from Scotland.
  Here you'll find my posts about all sorts of things - expect baking, programming and photography.
baseurl: "/"
url: "https://rorydbain.github.io"
github_username:  rorydbain
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 6
paginate_path: /page:num/
sass:
  sass_dir: assets
