title: To Make A Long Rory Short
email: rorydbain@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Rory Bain, I'm a software developer living in Edinburgh.
  Here you will find various things that I find interesting. 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://rorydbain.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rorydbain
instagram_username: rorybain

# Build settings
markdown: redcarpet
theme: minima
plugins:
  - jekyll-feed
  - jekyll-picture-tag

disqus:
  shortname: www-roryba-in

google_analytics: UA-114754770-1

picture:
  source: "assets/images/_fullsize"
  output: "assets/images"
  markup: "picture"
  presets:
    default:
      attr:
        class: "gallery-pict"
      ppi: [1, 1.5, 2.0]
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
      source_default:
        width: "600"
